Domain\Entities\Product:
  type: entity
  table: products
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      column: name
      nullable: false
      length: 255
      options:
        fixed: false
    priceInUSD:
      type: string
      column: price_in_usd
      nullable: false
      length: 255
      options:
        fixed: false
  manyToOne:
    offer:
      targetEntity: Domain\Entities\Offer
      inversedBy: products
      joinColumn:
        name: offer_id
        referencedColumnName: id
